name: Deploy AI Chat Example to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'examples/ai-chat-example/**'
      - '.github/workflows/deploy-ai-chat-example.yml'
  workflow_dispatch:

jobs:
  deploy-ai-chat:
    uses: ./.github/workflows/cloudflare-deploy-reusable.yml
    with:
      working-directory: ./examples/ai-chat-example
      project-name: unify-ai-chat
      branch-name: main
      build-command: npm run build
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 